baseURL = "/"
disableLanguages = []
disqusShortname = ""
googleAnalytics = ""
languageCode = "en-us"
languageName = "En"
paginate = "6"
summaryLength = "10"
theme = "github.com/themefisher/twenty-twenty-hugo"
title = "TADZIU"
[markup.goldmark.renderer]
unsafe = true
[[menu.desktop]]
URL = "contact"
name = "Contact"
weight = 1
[[menu.main]]
URL = "/"
name = "Home"
weight = 1
[[menu.main]]
URL = "about"
name = "About"
weight = 2
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 3
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 4
[[menu.main]]
URL = "sample-page"
name = "Sample Page"
weight = 5
[outputs]
home = ["HTML", "RSS", "JSON"]
[params]
author = "Themefisher"
description = "This is meta description"
[params.banner]
heading = "Crypto is changing the music industry and Tadziu is a pioneering musician at the frontier of this change"
image = "images/2020-landscape-1-2.png"
[params.blog]
heading = "Music, meditation, improvisation, and collaboration. Check out blog posts below or go to the About page to learn more about me."
[params.call_to_action]
button_label = "Contact Us"
button_url = "contact"
content = "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis"
enable = true
title = "Contact us for more information."
[params.footer]
address = "Planet Earth"
content = "I created this site using Fleek as a hosting service. I was able to make this site without any coding knowledge using a Hugo template with Forestry.io "
copyright = "Copyright &copy; 2020 a hugo theme by [themefisher](https://themefisher.com) ported from [WordPress Twenty Twenty](https://github.com/WordPress/twentytwenty)"
hours = "The average person lives for about 610,000 hours, don't let them pass you by ;)"
title = "About This Site"
[params.gallery]
enable = true
[[params.gallery.gallery_item]]
image = "images/2020-square-2.png"
[[params.gallery.gallery_item]]
image = "images/2020-square-1.png"
[params.social]
email = "#"
facebook = "#https://audius.co/tadziu"
instagram = "#https://www.youtube.com/channel/UClQnUq5ApkQxVZ6zBu3XMCw"
linkedin = "#"
twitter = "#https://twitter.com/TadziuMusic"
yelp = "#https://open.spotify.com/artist/5FOmDC8iLQ6ZSFXJsCbFpn?si=is3e2j7qRE6jtdDi9ARVvg"
[taxonomies]
author = "author"
category = "categories"
tag = "tags"
